/*
 * This file contains definitions gathered from
 * http://www.w3.org/TR/2013/REC-performance-timeline-20131212/
 */

interface PerformanceEntry {
  readonly attribute DOMString name;
  readonly attribute DOMString entryType;
  readonly attribute DOMHighResTimeStamp startTime;
  readonly attribute DOMHighResTimeStamp duration;
};

// Extension to the Performance interface
partial interface Performance {
  PerformanceEntryList getEntries();
  PerformanceEntryList getEntriesByType(DOMString entryType);
  PerformanceEntryList getEntriesByName(DOMString name, optional DOMString entryType);
};

typedef sequence <PerformanceEntry> PerformanceEntryList;
